In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
import pickle
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

mnist = fetch_openml('mnist_784', as_frame=False)
print(mnist.keys())

C:\Users\karol\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])


In [2]:
X, y = mnist["data"], mnist["target"].astype(np.uint8)
print(X.shape, y.shape)
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]

(70000, 784) (70000,)


In [3]:
X_train, X_test, y_train, y_test = train_test_split(mnist.data, mnist.target, test_size=0.2, random_state=42)

In [4]:
###Exercise 4
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
sgd_clf = SGDClassifier(random_state=42)
y_train_0 = (y_train == '0')
sgd_clf.fit(X_train, y_train_0)

SGDClassifier(random_state=42)

In [5]:
train_acc = sgd_clf.score(X_train, y_train_0)
test_acc = sgd_clf.score(X_test, y_test_0)
print(train_acc)
print(test_acc)

0.9918571428571429
0.9077142857142857


In [6]:
with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump([train_acc, test_acc], f)

In [7]:
cv_scores = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy", n_jobs=-1)
print(cv_scores)

[0.98687523 0.98762522 0.98649952]


In [8]:
with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(cv_scores, f)

In [9]:
###Exercise 5
sgd_clff = SGDClassifier(random_state=42)
sgd_clff.fit(X_train, y_train)

y_test_pred = sgd_clff.predict(X_test)
cmx = confusion_matrix(y_test, y_test_pred)
print(cmx)

[[1213    1   34    7    0   20   16    2   11   39]
 [   0 1565    6    6    2    7    2    2    3    7]
 [   0   18 1212   33    8   11   23   17   46   12]
 [   0    8   55 1205    0   67    5   15   16   62]
 [   0    5   32    5  919    9   18   41   39  227]
 [   3    8   18   41    5 1064   21    9   57   47]
 [   1    1   29    1    3   20 1327    4    7    3]
 [   3    3   22    5    4    5    0 1411    1   49]
 [   2   21   27   60    3   58   25   10 1009  142]
 [   1    6   14   12    8    2    1   85   12 1279]]


In [10]:
with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(np.array(cmx), f)